### ISSUE TITLE
HostsController#active etc: wrong number of arguments (1 for 0) (ArgumentError)

### ISSUE THREAD

**Issue by domcleal** [theforeman/foreman_host_rundeck#8]
This plugin causes errors on a few actions in Foreman core, e.g. HostsController#active which calls the index method with one argument.  The plugin adds a method chain that doesn't accept any arguments, when the index method usually takes one optional arg.

<pre>
wrong number of arguments (1 for 0) (ArgumentError)
/var/lib/workspace/workspace/test_plugin_matrix@3/database/sqlite3/ruby/2.1/plugin/app/controllers/concerns/foreman_host_rundeck/hosts_controller_extensions.rb:10:in `index_with_rundeck'
/var/lib/workspace/workspace/test_plugin_matrix@3/database/sqlite3/ruby/2.1/foreman/app/controllers/hosts_controller.rb:493:in `errors'
</pre>

You should be able to see this by running the core functional tests for HostsController.

Once fixed, we can enable testing in Jenkins: http://projects.theforeman.org/projects/foreman/wiki/Jenkins#Foreman-plugin-testing

**Comment by domcleal** [comment]
Fixed in #9.
